title: Talha Amin
logo: /assets/Talha_circle.jpeg
description: MS Business Analytics Candidate @ UC Davis | Data Analytics | Marketing Analytics | Machine Learning | Agentic AI
theme: jekyll-theme-minimal
